# Generated by Django 4.1 on 2023-01-17 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0002_alter_students_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pokemon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("rarity", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Students",
        ),
    ]
