# Generated by Django 4.1 on 2023-01-07 14:15

import django.contrib.auth.models
from django.db import migrations, models
import payment.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.CharField(
                        max_length=20, verbose_name=payment.models.Product
                    ),
                ),
                (
                    "buyer",
                    models.CharField(
                        max_length=20, verbose_name=django.contrib.auth.models.User
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("price", models.FloatField()),
            ],
        ),
    ]
