# Generated by Django 4.1 on 2023-01-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="img",
            field=models.CharField(default="img", max_length=200),
            preserve_default=False,
        ),
    ]
