# Generated by Django 4.1 on 2023-01-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_product_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="link",
            field=models.CharField(default="/payment/pay", max_length=200),
            preserve_default=False,
        ),
    ]
