# Generated by Django 4.1 on 2023-01-08 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0003_product_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="link",
        ),
    ]
