# Generated by Django 4.1 on 2023-01-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0004_remove_product_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
