# Generated by Django 4.1 on 2023-01-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0006_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="my_id",
            field=models.IntegerField(default="0", max_length=200),
        ),
    ]
