# Generated by Django 4.1 on 2023-01-20 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0007_product_my_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="my_id",
        ),
    ]
