# Generated by Django 4.1 on 2023-01-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_profile_date_modified"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="money",
            field=models.IntegerField(default=110, max_length=25),
            preserve_default=False,
        ),
    ]
