# Generated by Django 4.1 on 2023-01-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_alter_profile_money"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="money",
            field=models.IntegerField(verbose_name=100),
        ),
    ]
