# Generated by Django 4.1 on 2023-01-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_alter_profile_money"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="money",
            field=models.IntegerField(),
        ),
    ]
