# Generated by Django 4.1 on 2023-01-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0009_alter_profile_money"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="money",
            field=models.IntegerField(default=100),
        ),
    ]
