# Generated by Django 4.1 on 2023-01-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0010_alter_profile_money"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="my_objects",
            field=models.CharField(default=[0, 0, 0], max_length=40),
        ),
    ]
