# Generated by Django 4.1 on 2023-01-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0011_profile_my_objects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="my_objects",
            field=models.CharField(default=[0, 0, 0, 0], max_length=40),
        ),
    ]
