# Generated by Django 4.1 on 2023-01-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_alter_profile_my_objects"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="my_pokemons",
            field=models.CharField(default=[0, 0, 0, 0], max_length=4000),
        ),
        migrations.AlterField(
            model_name="profile",
            name="my_objects",
            field=models.CharField(default=[0, 0, 0, 0], max_length=400),
        ),
    ]
