# Generated by Django 4.1 on 2023-02-01 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0014_nav_settings"),
    ]

    operations = [
        migrations.RenameField(
            model_name="nav_settings",
            old_name="bool",
            new_name="display",
        ),
    ]
