# Generated by Django 4.1 on 2023-01-21 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("letschat", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Room",
        ),
        migrations.AlterField(
            model_name="message",
            name="date",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2023, 1, 21, 21, 21, 30, 290994)
            ),
        ),
    ]
