# Generated by Django 4.1 on 2023-01-31 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("letschat", "0008_alter_message_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="LastRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_name", models.CharField(max_length=1000000)),
            ],
        ),
        migrations.AlterField(
            model_name="message",
            name="date",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2023, 1, 31, 8, 48, 50, 3509)
            ),
        ),
    ]
