# Generated by Django 4.1 on 2023-02-01 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("letschat", "0011_alter_message_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="date",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2023, 2, 1, 16, 16, 6, 810171)
            ),
        ),
    ]
