# Generated by Django 4.1 on 2023-02-07 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("letschat", "0012_alter_message_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="date",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2023, 2, 7, 15, 53, 39, 440363)
            ),
        ),
    ]
